### ISSUE TITLE
does not remove the original preview

### ISSUE THREAD

**Issue by github-olivier-abdesselam** [Kyrela/FixTweetBot#4]
![image](https://github.com/Kyrela/FixTweetBot/assets/88483628/c70d3d42-c069-45f2-bee4-a317376cc15a)

**Comment by Kyrela** [comment]
Hopefully this will fix the problem. Can you give me a feedback on it in like 2-3 days, to see if this issue still happens?  Also please make sure the bot has proper permissions with the `/about` command.

**Comment by github-olivier-abdesselam** [comment]
Thanks !

**Comment by github-olivier-abdesselam** [comment]
Looks like it's working, will update the ticket if it keeps on happening

**Comment by Kyrela** [comment]
Found one occurence of this bug:
![image](https://github.com/Kyrela/FixTweetBot/assets/44508673/1d389ea3-d616-4725-90c3-d4122fe3ba7b)

**Comment by Kyrela** [comment]
Deloyed a new version that should fix this bug. Please update this issue if it happens again. Will close it in the next week if i don't find any occurence of this bug

**Comment by Kyrela** [comment]
Closed, don't hesitate to re-open it if it happens again.
